### ISSUE TITLE
Unable to download DB (DB.zip is corrupted)

### ISSUE THREAD

**Issue by ASUQ** [HubertTang/PLASMe#11]
Error while downloading the DB. (Step 3 Download the reference database using ```PLASMe_db.py```)

Environment:
CentOS Linux release 8.5.2111
Linux version 4.18.0
Conda version 23.9.0
Mamba version 1.5.6

```
python PLASMe_db.py
Downloading DB.zip ... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   245  100   245    0     0    383      0 --:--:-- --:--:-- --:--:--   382
Verifying md5 ... 
DB.zip is incomplete or corrupted, please rerun the script to redownload the database.
Unzip the reference plasmid database ... ...
Traceback (most recent call last):
  File "~/PLASMe/PLASMe_db.py", line 181, in <module>
    plasme_db(keep_zip=plasmedb_args.keep_zip, 
  File "~/PLASMe/PLASMe_db.py", line 158, in plasme_db
    shutil.unpack_archive(f"{plasme_full_path}/DB.zip", plasme_full_path)
  File "~/Conda_envs/PLASMe/lib/python3.9/shutil.py", line 1271, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "~/Conda_envs/PLASMe/lib/python3.9/shutil.py", line 1170, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: ~/PLASMe/DB.zip is not a zip file
```

**Comment by HubertTang** [comment]
Hi ASUQ,

It appears that the data was interrupted during the download process, causing the downloaded file to be damaged. You can delete the damaged zip file and rerun the script, which will re-download it. Alternatively, you can try to download the database manually.

> Download the reference dataset (12.4GB) manually from [Zenodo](https://zenodo.org/record/8046934/files/DB.zip?download=1) ([OneDrive](https://portland-my.sharepoint.com/:u:/g/personal/xubotang2-c_my_cityu_edu_hk/ERYxOA6rEUVLpyWyyWRECWABFKb4F51IYmGlobFvH8GTLw?e=W2zl00)) to the same directory with PLASMe.py. (No need to uncompress it, PLASMe will extract the files and build the database the first time you use it. It will take several minutes.)

Best,
Xubo

**Comment by ASUQ** [comment]
Hello Xubo,

Thanks for the reply.
I found out that I reached the volume capacity while downloading the file.

Can I download the database to the other directory and specify the database file path using certain option like '--db')?

**Comment by HubertTang** [comment]
Hi ASUQ,

Sorry for the late reply. I have added an `--database` option to specify the database path. I also updated its usage in README:

> **Alternative 2:**
> 
> Download the reference dataset (12.4GB) manually from [[Zenodo](https://zenodo.org/record/8046934/files/DB.zip?download=1)](https://zenodo.org/record/8046934/files/DB.zip?download=1) ([[OneDrive](https://portland-my.sharepoint.com/:u:/g/personal/xubotang2-c_my_cityu_edu_hk/ERYxOA6rEUVLpyWyyWRECWABFKb4F51IYmGlobFvH8GTLw?e=W2zl00)](https://portland-my.sharepoint.com/:u:/g/personal/xubotang2-c_my_cityu_edu_hk/ERYxOA6rEUVLpyWyyWRECWABFKb4F51IYmGlobFvH8GTLw?e=W2zl00)) to the any directory and uncompress it, you will obtain a database folder named `DB`. When using `PLASMe.py`, use the `-d` option to specify the `DB`'s absolute path (not relative path).

**Comment by asuq** [comment]
Thank you!
